### PR TITLE
X11fullscreen

### PR DESCRIPTION
**Pull request by G3rb**
clean

### CODE REVIEW

**Comment by fduncanh** [comment]
@G3rb Your pull request is committed in branch x11fullscreen.   A few small changes are added (you can look at them on github), and I altered the cmake CMakelists.txt so X_DISPLAY_FIX is used by default if the X11 development libraries are installed, (unless -DNO_X11_DEPS=ON is specified with cmake).

(So "-DZOOMFIX=ON" is gone)

Please test.

I would like make  the -fs option  set the initial value of fullscreen to "true" (easy) and then make the initial X11 screen to be in fullscreen mode if the initial value of fullscreen is "true", but I did not get it to work. 

I thought an initial  call to 
```
set_fullscreen(renderer->gst_window->display, renderer->gst_window->window, renderer->server_name, &fullscreen);  
```
(just after gst_window->window is obtained) would work but either I did something wrong or something else is needed.

**Comment by G3rb** [comment]
Thanks a lot ! I can't test it today but I will do that this monday. The -fs option will be useful !

**Comment by fduncanh** [comment]
after some more cleanups, uxplay -fs now starts in fullscreen mode with X11 windows

**Comment by fduncanh** [comment]
Its now all merged into the master branch of UxPlay.

Thanks for finding out how to do this!

I added Alt-Enter as a second key shortcut as well as F11, and now -fs puts one into full screen mode initially.

**Comment by G3rb** [comment]
Thanks to you !, I test it just now and everything works fine on Ubuntu20.04 (compiled with no options).

**Pull request closed without merging**
