### PR TITLE
append changelog to fulfill the license obligation

### PR DESCRIPTION
**Pull request by xiayingfeng**
### Missing notice for modifications on original work (violation of [GPL-3.0](https://opensource.org/licenses/GPL-3.0))

[**Modification terms and conditions in license**] The original work should be honored while the modifications on it should be attached with prominent notices as the license [GPL-3.0](https://opensource.org/licenses/GPL-3.0) dictates. Your project is a forking project from [antimof/UxPlay](https://github.com/antimof/UxPlay) which adopts [GPL-3.0](https://opensource.org/licenses/GPL-3.0) as its project license. The modification terms and conditions of [GPL-3.0](https://opensource.org/licenses/GPL-3.0) dictate that:

>[GPL-3.0](https://opensource.org/licenses/GPL-3.0):
>
>*...The work must carry prominent notices stating that you modified it, and giving a relevant date...*

Therefore, I think the project is obligated to abide by the modification terms and conditions in [GPL-3.0](https://opensource.org/licenses/GPL-3.0).

[**Violation of modification terms and conditions**] I run through your history, and it turns out that you have conducted modifications to the *source files* of original work while didn't provide prominent notices. You have **19** commits which conduct modifications to the original work, all of which are not declared in [README.html](https://github.com/FDH2/UxPlay/blob/master/README.html), [README.md](https://github.com/FDH2/UxPlay/blob/master/README.md), [README.txt](https://github.com/FDH2/UxPlay/blob/master/README.txt). Specifically, of the **19** commits, **all** commits are not announced in these files. According to the license terms and conditions above, it is regarded as license violation. Thus, to avoid potential legal risks, I would suggest you carry out prominent notices for the **19** commits. 

[**Fix**] For your convenience, I created a PR with by picking up modification-related commit messages. It adds a few lines in [changelog](https://github.com/xiayingfeng/UxPlay/blob/fulfill-license-obligation/changelog) without touching the codebase. Please be comfortable to check it out. 

Full details of the report you could refer to the [html](https://htmlpreview.github.io/?https://github.com/xiayingfeng/UxPlay/blob/master/page.html) file attached. Hope it helps!

Cheers!

### CODE REVIEW

**Comment by fduncanh** [comment]
most of this is computer-generated nonsense.   The README document is not part of the code and is not "GPL".  

I will however add my name and date to the copyright notices on code files I have modified .

**Comment by fduncanh** [comment]
Actually, this is a fork of RPiPlay, just not done through GitHub.

* antimov  downloaded  the RPiPlay  code, and modified it to add GStreamer renderers instead of OpenMax, and created a new project GitHub  UxPlay with it during  three weeks April 15-May 7 2020.   The Github fork mechanism was not used.

*antimov's code and GitHub history was completely pulled  back into RPiPlay on Sept 4 2020.

* antimov has not worked on the code since then.   There are no attributions to antimov in the code, and none are needed because it all went back into RPiPlay.

* On July 31, 2021, I forked the antimov github site, and updated with the changes made  up till then in RpiPlay.

I then diverged from the RpiPlay code base as of August 1, 2020.

I will add my name and modification dates to the files I have modified.

**Comment by xiayingfeng** [comment]
Thank you for your review, after considering your comment and communicating with open source organization, 
we will recommend an alternative to other open source contributors, which is: 
put a note in the top directory, something like MODIFICATION.md, and write "In compliance with the license: I declare that this version of the program contains my modifications, which can be seen through the usual "git" mechanism."

**Comment by fduncanh** [comment]
Not everything is done through git.

Also you don't have standing to start issuing  automated "notices of GPL violations".     My understanding is that only the previous authors have standing to to that.   There is no place for self-appointed GPL regulators.

**Pull request closed without merging**
