### PR TITLE
Remove -march=native flag to make packaging friendly

### PR DESCRIPTION
**Pull request by WUGqnwvMQPzl**
I'm using Arch Linux and [archlinuxcn repository](https://github.com/archlinuxcn/repo) have pre-built UxPlay package (uxplay-git), but when I try to use it, program just throws "Illegal instruction" error and exits.

After asking people on Arch Linux CN community, someone pointed out it may be compiled with `-march=native` flag, and I found that flag on cmakelists file.

So I removed the flag and recompile it, things still works and hopefully it can fix "Illegal instruction" error on pre-built package on software repositories.

### CODE REVIEW

**Comment by fduncanh** [comment]
Sounds fine.  These CFLAGS are inherited from initial versions  of UxPlay, and I  don't really understand them.  Can you review all of them them and see if anything else should be changed.

**Comment by fduncanh** [comment]
Looking at this its clear that -march=native is not wanted for packaging, but might be wanted when compiling for one self.
Does the AUR package have a script?    I could make a cmake optiion line '-DNO_MARCH_NATIVE=ON" to omit it when packaging?

```
Optimized CFLAGS for modern processors

CFLAGS="-O2 -pipe -march=native" makes gcc enable all the features of the CPU it is running on. That's great as long as you do not plan on running the resulting binaries on another computer ever. You may want to do that and optimize for modern processors.. Having your cake and eating it is tricky so some compromises are required. One you may accept is to optimize for desktop computers made after 2015. That gives you:

    -mcx16 # CMPXCHG16B, AMD64 2005
    -mmmx -msse -msse2 # Intel 2001, AMD 2003
    -msse3 # Intel 2004, AMD 2007
    -mssse3 # Intel 2006, AMD 2011
    -msse4.1 -msse4.2 # Intel 2008, AMD 2011
    -mavx # Intel 2011, AMD 2011
    -mavx2 # Intel 2013, AMD 2015
```

**Comment by WUGqnwvMQPzl** [comment]
> These CFLAGS are inherited from initial versions of UxPlay, and I don't really understand them. Can you review all of them and see if anything else should be changed.

I'm not good at C programming either, so I'm afraid I cannot reviewing all flags, sorry.

> Does the AUR package have a script? I could make a cmake optiion line '-DNO_MARCH_NATIVE=ON" to omit it when packaging?

You can view the AUR packaging script from their webpage like this:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=uxplay-git
It just compiles from `cmake` and package it.

Anyway, add the `-DNO_MARCH_NATIVE` option sounds a good idea.

**Comment by fduncanh** [comment]
I checked how RPiPlay does it now, and I see that now it has 

```
# Common x86/x86_64 cflags
if( CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)" )
    set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Ofast -march=native" )
endif()
```

so I did the same in UxPlay. (now  in github)
I am guessing that the "illegal instruction" is in builds on Arm  (Raspberry Pi?) not intel x8/x86_64 ?

is that correct?

If so, this should fix the problem with future builds.

**Comment by WUGqnwvMQPzl** [comment]
> I checked how RPiPlay does it now, and I see that now it has
> 
> ```
> # Common x86/x86_64 cflags
> if( CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)" )
>     set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Ofast -march=native" )
> endif()
> ```
> 
> so I did the same in UxPlay. (now in github) I am guessing that the "illegal instruction" is in builds on Arm (Raspberry Pi?) not intel x8/x86_64 ?
> 
> is that correct?
> 
> If so, this should fix the problem with future builds.

Nope, I tried the latest git version of UxPlay on archlinuxcn repository, still gets the "illegal hardware instruction" error.

```
```

**Comment by fduncanh** [comment]
You are correct: -march=native should only be used for compiling something to run on the same machine it was compiled on.

I added a cmake option `cmake -DNO_MARCH_NATIVE=ON` to switch it off, and a cmake warning if the  -march=native option is used.    The -DNO_MARCH_NATIVE=ON cmake option should be added to the AUR build scripts.

**Comment by WUGqnwvMQPzl** [comment]
> You are correct: -march=native should only be used for compiling something to run on the same machine it was compiled on.
> 
> I added a cmake option `cmake -DNO_MARCH_NATIVE=ON` to switch it off, and a cmake warning if the -march=native option is used. The -DNO_MARCH_NATIVE=ON cmake option should be added to the AUR build scripts.
> 
> The change is:
> 
> ```
> # Common x86/x86_64 cflags
> if( NOT NO_MARCH_NATIVE AND CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)" )
>   set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=native" )
>   message( STATUS "Using CFLAGS with  -march=native" )
>   message( STATUS "*** ONLY USE THIS WHEN COMPILING ON THE MACHINE THAT WLL RUN UXPLAY" )
>   message( STATUS "  run \"cmake -DNO_MARCH_NATIVE=ON\" to switch off this compiler option" )
> endif()
> ```
> 
> I also replaced -Ofast by -O2

Tried compiling on my VPS and install it on my main AMD machine with that option, works like charm, thanks!

**Pull request closed without merging**
