### PR TITLE
fixed issue: correct the calculation of lost packets when sequence number wraps around

### PR DESCRIPTION
**Pull request by kgbook**
Suppose `seqnum` wraps around to `0`, and the value of `first_seqnum` is `UINT16_MAX `, then the `count` should be `0` rather than `UINT16_MAX `.

### CODE REVIEW

**Comment by fduncanh** [comment]
Thanks for the PR!

Did you actually have an error due to this, or is this from reading the code?

I see that both count and seqnum are defined as int in  `raop_buffer_handle_resends`, rather than unsigned shorts.
maybe this is the error that needs fixing?


```

void raop_buffer_handle_resends(raop_buffer_t *raop_buffer, raop_resend_cb_t resend_cb, void *opaque) {
    assert(raop_buffer);
    assert(resend_cb);

    if (seqnum_cmp(raop_buffer->first_seqnum, raop_buffer->last_seqnum) < 0) {
        int seqnum, count;   <-------------------------------------------------- ERROR?
        logger_log(raop_buffer->logger, LOGGER_DEBUG, "raop_buffer_handle_resends first_seqnum=%u last seqnum=%u",
                   raop_buffer->first_seqnum, raop_buffer->last_seqnum);
        for (seqnum = raop_buffer->first_seqnum; seqnum_cmp(seqnum, raop_buffer->last_seqnum) < 0; seqnum++) {
            raop_buffer_entry_t *entry = &raop_buffer->entries[seqnum % RAOP_BUFFER_LENGTH];
            if (entry->filled) {
                break;
            }
        }
        if (seqnum_cmp(seqnum, raop_buffer->first_seqnum) == 0) {
            return;
        }
        count = seqnum_cmp(seqnum, raop_buffer->first_seqnum);
        resend_cb(opaque, raop_buffer->first_seqnum, count);
    }
}

```

**Comment by fduncanh** [comment]
I looks like the error dates to July 2019 in the earlier RPiPlay code

**Comment by fduncanh** [comment]
I think that seqnum should be an unsigned short, and maybe count also be unsigned short, given by

```
count = seqnum - raop_buffer->first seqnum
```
??

**Comment by fduncanh** [comment]
I verified that secnum_cmp works correctly.      I think the corrected code that is wrap-around-safe is (see below)
* @kgbook do you agree?


```
void raop_buffer_handle_resends(raop_buffer_t *raop_buffer, raop_resend_cb_t resend_cb, void *opaque) {
    assert(raop_buffer);
    assert(resend_cb);

    if (seqnum_cmp(raop_buffer->first_seqnum, raop_buffer->last_seqnum) < 0) {
        unsigned short  seqnum, count;   
        logger_log(raop_buffer->logger, LOGGER_DEBUG, "raop_buffer_handle_resends first_seqnum=%u last seqnum=%u",
                   raop_buffer->first_seqnum, raop_buffer->last_seqnum);
        for (seqnum = raop_buffer->first_seqnum; seqnum_cmp(seqnum, raop_buffer->last_seqnum) < 0; seqnum++) {
            raop_buffer_entry_t *entry = &raop_buffer->entries[seqnum % RAOP_BUFFER_LENGTH];
            if (entry->filled) {
                break;
            }
        }
        if (seqnum_cmp(seqnum, raop_buffer->first_seqnum) == 0) {
            return;
        }
        count = seqnum -  raop_buffer->first_seqnum);
        resend_cb(opaque, raop_buffer->first_seqnum, count);
    }
}
```

**Comment by fduncanh** [comment]
This is probably a cleaner fix?
* @kgbook , what do you think?   If you have seen errors, does this fix them?

```
void raop_buffer_handle_resends(raop_buffer_t *raop_buffer, raop_resend_cb_t resend_cb, void *opaque) {
    assert(raop_buffer);
    assert(resend_cb);

    if (seqnum_cmp(raop_buffer->first_seqnum, raop_buffer->last_seqnum) < 0) {
        unsigned short  seqnum, count = 0;     
        logger_log(raop_buffer->logger, LOGGER_DEBUG, "raop_buffer_handle_resends first_seqnum=%u last seqnum=%u",
                   raop_buffer->first_seqnum, raop_buffer->last_seqnum);
        for (seqnum = raop_buffer->first_seqnum; seqnum_cmp(seqnum, raop_buffer->last_seqnum) < 0; seqnum++) {
            raop_buffer_entry_t *entry = &raop_buffer->entries[seqnum % RAOP_BUFFER_LENGTH];
            if (entry->filled) {
                break;
            }
            count++;                           
        }
        if (count ) {
            resend_cb(opaque, raop_buffer->first_seqnum, count);
        }
}
```

**Comment by fduncanh** [comment]
we will close this PR, but please give feedback

Thank you again @kgbook

**Comment by kgbook** [comment]
sorry for reply late. 
```cpp
#include <iostream>

static short seqnum_cmp(unsigned short s1, unsigned short s2)
{
  return (s1 - s2);
}

int main() {
  unsigned short s1 = 65535;
  unsigned short s2 = 0;
  unsigned short q1 = 0;
  unsigned short q2 = 65535;
  std::cout << "s1: " << s1 << ", s2: " << s2 <<", seqnum_cmp(s1,s2): "<<seqnum_cmp(s1, s2)  << std::endl;
  std::cout << "q1: " << q1 << ", q2: " << q2 <<", seqnum_cmp(q1,q2): "<<seqnum_cmp(q1, q2)  << std::endl;
  return 0;
}
```
Output:
s1: 65535, s2: 0, seqnum_cmp(s1,s2): -1
q1: 0, q2: 65535, seqnum_cmp(q1,q2): 1

There is some difference between our project and UxPlay. And this is not issue in UxPlay, as you say. 
Thanks!

**Pull request closed without merging**
